# Imagine you have raw data from a source system stored in databricks, under path- catalog->Dummy_DBT_Project->schema->source
# we have customers, orders, order_items, products and payments tables.

sources:

    - name: source
      database: Dummy_DBT_Project
      schema: source

      config:
        freshness:                  # In order to run source freshness run: dbt source freshness
            warn_after:
                count: 12
                period: hour
            error_after:
                count: 24
                period: hour

        loaded_at_field: etl_loaded_at

      tables:

        - name: customers
          
          columns:

            - name: customer_id
              data_tests:
                - not_null
                - unique

            - name: first_name
              data_tests:
                - not_null
            - name: last_name
              data_tests:
                -not_null
            - name: email
              data_tests:
                - not_null
                - unique
            - name: country
              data_tests:
                - not_null
                - unique
            - name: created_at
              data_tests:
                - not_null
            - name: updated_at
              data_tests:
                - not_null

# In this way you can define all tables and there respective columns on which you need to perform tests